/*
 * This file is generated by jOOQ.
 */
package com.only4play.auth.db.tables.records;


import com.only4play.auth.db.tables.AuthAdminUser;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthAdminUserRecord extends UpdatableRecordImpl<AuthAdminUserRecord> implements Record10<Long, Timestamp, Timestamp, String, String, String, Long, String, String, Integer> {

    private static final long serialVersionUID = -794366048;

    /**
     * Setter for <code>authserver.auth_admin_user.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>authserver.auth_admin_user.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>authserver.auth_admin_user.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>authserver.auth_admin_user.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>authserver.auth_admin_user.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>authserver.auth_admin_user.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>authserver.auth_admin_user.username</code>.
     */
    public void setUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>authserver.auth_admin_user.username</code>.
     */
    public String getUsername() {
        return (String) get(3);
    }

    /**
     * Setter for <code>authserver.auth_admin_user.phone</code>.
     */
    public void setPhone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>authserver.auth_admin_user.phone</code>.
     */
    public String getPhone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>authserver.auth_admin_user.password</code>.
     */
    public void setPassword(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>authserver.auth_admin_user.password</code>.
     */
    public String getPassword() {
        return (String) get(5);
    }

    /**
     * Setter for <code>authserver.auth_admin_user.depart_id</code>.
     */
    public void setDepartId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>authserver.auth_admin_user.depart_id</code>.
     */
    public Long getDepartId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>authserver.auth_admin_user.depart_name</code>.
     */
    public void setDepartName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>authserver.auth_admin_user.depart_name</code>.
     */
    public String getDepartName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>authserver.auth_admin_user.valid_status</code>.
     */
    public void setValidStatus(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>authserver.auth_admin_user.valid_status</code>.
     */
    public String getValidStatus() {
        return (String) get(8);
    }

    /**
     * Setter for <code>authserver.auth_admin_user.version</code>.
     */
    public void setVersion(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>authserver.auth_admin_user.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Timestamp, Timestamp, String, String, String, Long, String, String, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, Timestamp, Timestamp, String, String, String, Long, String, String, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AuthAdminUser.AUTH_ADMIN_USER.ID;
    }

    @Override
    public Field<Timestamp> field2() {
        return AuthAdminUser.AUTH_ADMIN_USER.CREATE_TIME;
    }

    @Override
    public Field<Timestamp> field3() {
        return AuthAdminUser.AUTH_ADMIN_USER.UPDATE_TIME;
    }

    @Override
    public Field<String> field4() {
        return AuthAdminUser.AUTH_ADMIN_USER.USERNAME;
    }

    @Override
    public Field<String> field5() {
        return AuthAdminUser.AUTH_ADMIN_USER.PHONE;
    }

    @Override
    public Field<String> field6() {
        return AuthAdminUser.AUTH_ADMIN_USER.PASSWORD;
    }

    @Override
    public Field<Long> field7() {
        return AuthAdminUser.AUTH_ADMIN_USER.DEPART_ID;
    }

    @Override
    public Field<String> field8() {
        return AuthAdminUser.AUTH_ADMIN_USER.DEPART_NAME;
    }

    @Override
    public Field<String> field9() {
        return AuthAdminUser.AUTH_ADMIN_USER.VALID_STATUS;
    }

    @Override
    public Field<Integer> field10() {
        return AuthAdminUser.AUTH_ADMIN_USER.VERSION;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Timestamp component2() {
        return getCreateTime();
    }

    @Override
    public Timestamp component3() {
        return getUpdateTime();
    }

    @Override
    public String component4() {
        return getUsername();
    }

    @Override
    public String component5() {
        return getPhone();
    }

    @Override
    public String component6() {
        return getPassword();
    }

    @Override
    public Long component7() {
        return getDepartId();
    }

    @Override
    public String component8() {
        return getDepartName();
    }

    @Override
    public String component9() {
        return getValidStatus();
    }

    @Override
    public Integer component10() {
        return getVersion();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Timestamp value2() {
        return getCreateTime();
    }

    @Override
    public Timestamp value3() {
        return getUpdateTime();
    }

    @Override
    public String value4() {
        return getUsername();
    }

    @Override
    public String value5() {
        return getPhone();
    }

    @Override
    public String value6() {
        return getPassword();
    }

    @Override
    public Long value7() {
        return getDepartId();
    }

    @Override
    public String value8() {
        return getDepartName();
    }

    @Override
    public String value9() {
        return getValidStatus();
    }

    @Override
    public Integer value10() {
        return getVersion();
    }

    @Override
    public AuthAdminUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AuthAdminUserRecord value2(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public AuthAdminUserRecord value3(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public AuthAdminUserRecord value4(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public AuthAdminUserRecord value5(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public AuthAdminUserRecord value6(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public AuthAdminUserRecord value7(Long value) {
        setDepartId(value);
        return this;
    }

    @Override
    public AuthAdminUserRecord value8(String value) {
        setDepartName(value);
        return this;
    }

    @Override
    public AuthAdminUserRecord value9(String value) {
        setValidStatus(value);
        return this;
    }

    @Override
    public AuthAdminUserRecord value10(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public AuthAdminUserRecord values(Long value1, Timestamp value2, Timestamp value3, String value4, String value5, String value6, Long value7, String value8, String value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthAdminUserRecord
     */
    public AuthAdminUserRecord() {
        super(AuthAdminUser.AUTH_ADMIN_USER);
    }

    /**
     * Create a detached, initialised AuthAdminUserRecord
     */
    public AuthAdminUserRecord(Long id, Timestamp createTime, Timestamp updateTime, String username, String phone, String password, Long departId, String departName, String validStatus, Integer version) {
        super(AuthAdminUser.AUTH_ADMIN_USER);

        set(0, id);
        set(1, createTime);
        set(2, updateTime);
        set(3, username);
        set(4, phone);
        set(5, password);
        set(6, departId);
        set(7, departName);
        set(8, validStatus);
        set(9, version);
    }
}
