/*
 * This file is generated by jOOQ.
 */
package com.only4play.auth.db.tables.records;


import com.only4play.auth.db.tables.AuthResource;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthResourceRecord extends UpdatableRecordImpl<AuthResourceRecord> implements Record12<Long, Long, Long, Integer, String, String, String, Long, Long, String, String, String> {

    private static final long serialVersionUID = -1428792598;

    /**
     * Setter for <code>authserver.auth_resource.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>authserver.auth_resource.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>authserver.auth_resource.created_at</code>.
     */
    public void setCreatedAt(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>authserver.auth_resource.created_at</code>.
     */
    public Long getCreatedAt() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>authserver.auth_resource.updated_at</code>.
     */
    public void setUpdatedAt(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>authserver.auth_resource.updated_at</code>.
     */
    public Long getUpdatedAt() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>authserver.auth_resource.version</code>.
     */
    public void setVersion(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>authserver.auth_resource.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>authserver.auth_resource.code</code>. 资源编码
     */
    public void setCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>authserver.auth_resource.code</code>. 资源编码
     */
    public String getCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>authserver.auth_resource.icon_class</code>.
     */
    public void setIconClass(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>authserver.auth_resource.icon_class</code>.
     */
    public String getIconClass() {
        return (String) get(5);
    }

    /**
     * Setter for <code>authserver.auth_resource.name</code>. 资源名称
     */
    public void setName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>authserver.auth_resource.name</code>. 资源名称
     */
    public String getName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>authserver.auth_resource.pid</code>. 父id
     */
    public void setPid(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>authserver.auth_resource.pid</code>. 父id
     */
    public Long getPid() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>authserver.auth_resource.platform_id</code>. 平台id
     */
    public void setPlatformId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>authserver.auth_resource.platform_id</code>. 平台id
     */
    public Long getPlatformId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>authserver.auth_resource.resource_desc</code>. 资源描述
     */
    public void setResourceDesc(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>authserver.auth_resource.resource_desc</code>. 资源描述
     */
    public String getResourceDesc() {
        return (String) get(9);
    }

    /**
     * Setter for <code>authserver.auth_resource.router</code>. 前端路由
     */
    public void setRouter(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>authserver.auth_resource.router</code>. 前端路由
     */
    public String getRouter() {
        return (String) get(10);
    }

    /**
     * Setter for <code>authserver.auth_resource.url</code>. 资源的url
     */
    public void setUrl(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>authserver.auth_resource.url</code>. 资源的url
     */
    public String getUrl() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, Long, Long, Integer, String, String, String, Long, Long, String, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, Long, Long, Integer, String, String, String, Long, Long, String, String, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AuthResource.AUTH_RESOURCE.ID;
    }

    @Override
    public Field<Long> field2() {
        return AuthResource.AUTH_RESOURCE.CREATED_AT;
    }

    @Override
    public Field<Long> field3() {
        return AuthResource.AUTH_RESOURCE.UPDATED_AT;
    }

    @Override
    public Field<Integer> field4() {
        return AuthResource.AUTH_RESOURCE.VERSION;
    }

    @Override
    public Field<String> field5() {
        return AuthResource.AUTH_RESOURCE.CODE;
    }

    @Override
    public Field<String> field6() {
        return AuthResource.AUTH_RESOURCE.ICON_CLASS;
    }

    @Override
    public Field<String> field7() {
        return AuthResource.AUTH_RESOURCE.NAME;
    }

    @Override
    public Field<Long> field8() {
        return AuthResource.AUTH_RESOURCE.PID;
    }

    @Override
    public Field<Long> field9() {
        return AuthResource.AUTH_RESOURCE.PLATFORM_ID;
    }

    @Override
    public Field<String> field10() {
        return AuthResource.AUTH_RESOURCE.RESOURCE_DESC;
    }

    @Override
    public Field<String> field11() {
        return AuthResource.AUTH_RESOURCE.ROUTER;
    }

    @Override
    public Field<String> field12() {
        return AuthResource.AUTH_RESOURCE.URL;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCreatedAt();
    }

    @Override
    public Long component3() {
        return getUpdatedAt();
    }

    @Override
    public Integer component4() {
        return getVersion();
    }

    @Override
    public String component5() {
        return getCode();
    }

    @Override
    public String component6() {
        return getIconClass();
    }

    @Override
    public String component7() {
        return getName();
    }

    @Override
    public Long component8() {
        return getPid();
    }

    @Override
    public Long component9() {
        return getPlatformId();
    }

    @Override
    public String component10() {
        return getResourceDesc();
    }

    @Override
    public String component11() {
        return getRouter();
    }

    @Override
    public String component12() {
        return getUrl();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCreatedAt();
    }

    @Override
    public Long value3() {
        return getUpdatedAt();
    }

    @Override
    public Integer value4() {
        return getVersion();
    }

    @Override
    public String value5() {
        return getCode();
    }

    @Override
    public String value6() {
        return getIconClass();
    }

    @Override
    public String value7() {
        return getName();
    }

    @Override
    public Long value8() {
        return getPid();
    }

    @Override
    public Long value9() {
        return getPlatformId();
    }

    @Override
    public String value10() {
        return getResourceDesc();
    }

    @Override
    public String value11() {
        return getRouter();
    }

    @Override
    public String value12() {
        return getUrl();
    }

    @Override
    public AuthResourceRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AuthResourceRecord value2(Long value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AuthResourceRecord value3(Long value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public AuthResourceRecord value4(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public AuthResourceRecord value5(String value) {
        setCode(value);
        return this;
    }

    @Override
    public AuthResourceRecord value6(String value) {
        setIconClass(value);
        return this;
    }

    @Override
    public AuthResourceRecord value7(String value) {
        setName(value);
        return this;
    }

    @Override
    public AuthResourceRecord value8(Long value) {
        setPid(value);
        return this;
    }

    @Override
    public AuthResourceRecord value9(Long value) {
        setPlatformId(value);
        return this;
    }

    @Override
    public AuthResourceRecord value10(String value) {
        setResourceDesc(value);
        return this;
    }

    @Override
    public AuthResourceRecord value11(String value) {
        setRouter(value);
        return this;
    }

    @Override
    public AuthResourceRecord value12(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public AuthResourceRecord values(Long value1, Long value2, Long value3, Integer value4, String value5, String value6, String value7, Long value8, Long value9, String value10, String value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthResourceRecord
     */
    public AuthResourceRecord() {
        super(AuthResource.AUTH_RESOURCE);
    }

    /**
     * Create a detached, initialised AuthResourceRecord
     */
    public AuthResourceRecord(Long id, Long createdAt, Long updatedAt, Integer version, String code, String iconClass, String name, Long pid, Long platformId, String resourceDesc, String router, String url) {
        super(AuthResource.AUTH_RESOURCE);

        set(0, id);
        set(1, createdAt);
        set(2, updatedAt);
        set(3, version);
        set(4, code);
        set(5, iconClass);
        set(6, name);
        set(7, pid);
        set(8, platformId);
        set(9, resourceDesc);
        set(10, router);
        set(11, url);
    }
}
