/*
 * This file is generated by jOOQ.
 */
package com.only4play.auth.db.tables.records;


import com.only4play.auth.db.tables.AuthRoleResource;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthRoleResourceRecord extends UpdatableRecordImpl<AuthRoleResourceRecord> implements Record6<Long, Long, Long, Integer, Long, Long> {

    private static final long serialVersionUID = 1136291986;

    /**
     * Setter for <code>authserver.auth_role_resource.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>authserver.auth_role_resource.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>authserver.auth_role_resource.created_at</code>.
     */
    public void setCreatedAt(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>authserver.auth_role_resource.created_at</code>.
     */
    public Long getCreatedAt() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>authserver.auth_role_resource.updated_at</code>.
     */
    public void setUpdatedAt(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>authserver.auth_role_resource.updated_at</code>.
     */
    public Long getUpdatedAt() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>authserver.auth_role_resource.version</code>.
     */
    public void setVersion(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>authserver.auth_role_resource.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>authserver.auth_role_resource.resource_id</code>. 资源Id
     */
    public void setResourceId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>authserver.auth_role_resource.resource_id</code>. 资源Id
     */
    public Long getResourceId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>authserver.auth_role_resource.role_id</code>. 角色id
     */
    public void setRoleId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>authserver.auth_role_resource.role_id</code>. 角色id
     */
    public Long getRoleId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Integer, Long, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, Integer, Long, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AuthRoleResource.AUTH_ROLE_RESOURCE.ID;
    }

    @Override
    public Field<Long> field2() {
        return AuthRoleResource.AUTH_ROLE_RESOURCE.CREATED_AT;
    }

    @Override
    public Field<Long> field3() {
        return AuthRoleResource.AUTH_ROLE_RESOURCE.UPDATED_AT;
    }

    @Override
    public Field<Integer> field4() {
        return AuthRoleResource.AUTH_ROLE_RESOURCE.VERSION;
    }

    @Override
    public Field<Long> field5() {
        return AuthRoleResource.AUTH_ROLE_RESOURCE.RESOURCE_ID;
    }

    @Override
    public Field<Long> field6() {
        return AuthRoleResource.AUTH_ROLE_RESOURCE.ROLE_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCreatedAt();
    }

    @Override
    public Long component3() {
        return getUpdatedAt();
    }

    @Override
    public Integer component4() {
        return getVersion();
    }

    @Override
    public Long component5() {
        return getResourceId();
    }

    @Override
    public Long component6() {
        return getRoleId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCreatedAt();
    }

    @Override
    public Long value3() {
        return getUpdatedAt();
    }

    @Override
    public Integer value4() {
        return getVersion();
    }

    @Override
    public Long value5() {
        return getResourceId();
    }

    @Override
    public Long value6() {
        return getRoleId();
    }

    @Override
    public AuthRoleResourceRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AuthRoleResourceRecord value2(Long value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AuthRoleResourceRecord value3(Long value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public AuthRoleResourceRecord value4(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public AuthRoleResourceRecord value5(Long value) {
        setResourceId(value);
        return this;
    }

    @Override
    public AuthRoleResourceRecord value6(Long value) {
        setRoleId(value);
        return this;
    }

    @Override
    public AuthRoleResourceRecord values(Long value1, Long value2, Long value3, Integer value4, Long value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthRoleResourceRecord
     */
    public AuthRoleResourceRecord() {
        super(AuthRoleResource.AUTH_ROLE_RESOURCE);
    }

    /**
     * Create a detached, initialised AuthRoleResourceRecord
     */
    public AuthRoleResourceRecord(Long id, Long createdAt, Long updatedAt, Integer version, Long resourceId, Long roleId) {
        super(AuthRoleResource.AUTH_ROLE_RESOURCE);

        set(0, id);
        set(1, createdAt);
        set(2, updatedAt);
        set(3, version);
        set(4, resourceId);
        set(5, roleId);
    }
}
