/*
 * This file is generated by jOOQ.
 */
package com.only4play.auth.db;


import com.only4play.auth.db.tables.AuthAdminUser;
import com.only4play.auth.db.tables.AuthResource;
import com.only4play.auth.db.tables.AuthRoleResource;
import com.only4play.auth.db.tables.AuthSysUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in authserver
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>authserver.auth_admin_user</code>.
     */
    public static final AuthAdminUser AUTH_ADMIN_USER = AuthAdminUser.AUTH_ADMIN_USER;

    /**
     * The table <code>authserver.auth_resource</code>.
     */
    public static final AuthResource AUTH_RESOURCE = AuthResource.AUTH_RESOURCE;

    /**
     * The table <code>authserver.auth_role_resource</code>.
     */
    public static final AuthRoleResource AUTH_ROLE_RESOURCE = AuthRoleResource.AUTH_ROLE_RESOURCE;

    /**
     * The table <code>authserver.auth_sys_user</code>.
     */
    public static final AuthSysUser AUTH_SYS_USER = AuthSysUser.AUTH_SYS_USER;
}
