spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/authserver?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false
debug: true
op:
  web:
    enable: true
    base-package: "com.only4play.auth"
    description: "auth service api"
    title: "auth service"
    version: "1.0.0"