// ---Auto Generated by Only4Play ---
package com.only4play.auth.model;

import io.swagger.annotations.ApiModel;
import lombok.Data;

@ApiModel
@Data
public class AdminUserVo extends BaseAdminUserVo {
}
